### ISSUE TITLE
App Router

### ISSUE THREAD

**Issue by andresfiloso** [Senbonzakura1234/use-pull-to-refresh#17]
Is this working for [App Router](https://nextjs.org/docs/app)? 

your example use `import { useRouter } from 'next/router';` that is not being used on App Router.

https://nextjs.org/docs/app/building-your-application/routing/linking-and-navigating#userouter-hook

**Comment by Senbonzakura1234** [comment]
@andresfiloso yes it's still work with the new router hook for app router

```typescript
export type UsePullToRefreshParams = {
	onRefresh: () => void | Promise<void>;
	// default value is 240
	maximumPullLength?: number;
	// default value is 180
	refreshThreshold?: number;
	isDisabled?: boolean;
};
```

As you can see, the hook is just taking in the `onRefresh` callback and run it when your pull action done, whatever the process inside `onRefresh` you feed into the hook is yours to manage, it could be anything not just router refresh function, such as invalidate request function call from [TanStack Query](https://tanstack.com/query/latest)
